
modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://forum.neutrongalaxy.epizy.com/" #optional
[[mods]] #mandatory
modId="neutrongalaxy" #mandatory
version="${file.jarVersion}" #mandatory
displayName="§1 Neutron Galaxy" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://neutrongalaxy.epizy.com/" #optional
logoFile="logo.png" #optional
credits="§e 3d modeling creator: Leviston §r§5 2d graphics designer: Miller_Craft §r§a Programing: MasterJ_Craft" #optional
authors="§2 MasterJ_Craft" #optional
description='''
§b This mods alows you to travel around the universe
'''